---
- name: Create a resource group
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: docker-rg
        location: westus
    - name: Create a virtual network
      azure_rm_virtualnetwork:
        resource_group: docker-rg
        name: docker_network
        address_prefixes: "10.0.0.0/16"
                 
    - name: Create a subnet
      azure_rm_subnet:
        resource_group: docker-rg
        virtual_network: docker_network
        name: hosts
        address_prefix: "10.0.1.0/24"

    - name: Create a public IP address
      azure_rm_publicipaddress:
       resource_group: docker-rg
       allocation_method: Static
       name: docker-ip

    - name: Create a Network Security Group and Open SSH port
      azure_rm_securitygroup:
        resource_group: docker-rg
        name: docker_nsg
        rules:
          - name: RDP
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 100
            direction: Inbound 
          - name: webpage
            protocol: "*"
            destination_port_range: 8080
            access: Allow
            priority: 110
            direction: Inbound 

    - name: Create a virtual network interface card
      azure_rm_networkinterface:
        resource_group: docker-rg
        name: docker_nic
        virtual_network: docker_network
        subnet: hosts
        public_ip_name: docker-ip
        security_group: docker_nsg            

    - name: Create a VM with a managed disk 
      azure_rm_virtualmachine:
        resource_group: docker-rg
        name: docker-vm
        admin_username: azuser
        admin_password: P@ssw0rd123
        managed_disk_type: Standard_LRS
        image:
          offer: 0001-com-ubuntu-server-focal
          publisher: canonical
          sku: 20_04-lts
          version: latest
        vm_size: Standard_D2s_v3
        os_type: Linux
        network_interfaces: docker_nic